### ISSUE TITLE
The icons aren't complete

### ISSUE THREAD

**Issue by lukaszciastko** [Azumgi/Material-Icons-Complete#2]
Despite the project name, not all material icons are included. For example, I couldn't find the 'deck' icon.

**Comment by Dreomite** [comment]
`deck` is the new icon that was not there 4 months ago when I released the font. The problem, however, is that I can't pull new icons with my script for some reason.

---

I investigated and found the problem. Google updated their site to use `https://fonts.google.com/metadata/icons` instead of `https://material.io/resources/icons/static/data.json` for listing icons.

However, they broke some things on their end. There were special icons with overridden download addresses, like [`settings`](https://github.com/Azumgi/Material-Icons-Complete/blob/master/glyphs/baseline/settings.svg) or [`star_rate`](https://github.com/Azumgi/Material-Icons-Complete/blob/master/glyphs/baseline/star_rate.svg) which were present in old `data.json` but are missing in new `icons` file. And you [won't be able to find](https://material.io/resources/icons/?search=settings&style=baseline) them.

I'm not sure if I want to spend my time on implementing a workaround for a currently broken site considering #1. For now, I'm just going to wait until Google fixes their site and maybe then I'll consider updating script and fonts, which I can't promise because I'm very busy with IRL projects and not motivated doing it overall.

**Comment by Dreomite** [comment]
I'm archiving this repository. If it's still relevant (which I highly doubt), you can take a look at https://github.com/material-icons/material-icons-font
